services:
  - type: web
    name: social-media-backend
    env: node
    rootDir: backend
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: MONGO_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: NODE_ENV
        value: production
      - key: CLIENT_ORIGIN
        sync: false

  - type: web
    name: social-media-frontend
    env: static
    rootDir: frontend
    buildCommand: npm run build
    staticPublishPath: dist
    envVars:
      - key: VITE_API_URL
        value: https://social-media-backend.onrender.com/api
